version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
