version: '3.6'
services:
  db:
    container_name: supabase-db
    build:
      context: ./postgres
    ports:
      - 5432:5432
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
